### ISSUE TITLE
First script assignment ready for grading

### ISSUE THREAD

**Issue by jsummerfield-matc** [madisoncollege-it-programs/python-scripting-jsummerfield-matc#1]
Should be good to go in the week2 folder! I wasn't completely sure if i had to create a variable for the thing i learned but i just printed it out without one since it didn't specifically say. Hope it is all good!

**Comment by cethenmc** [comment]
You only created this one issue for both assignments.  Don't worry about it this time.  Assignment #1 for Week 2 (that we did in class) looks good.  Will get to Assignment #2 for Week 2 before the end of the day on Friday.  I will close this issue once that is recorded in the gradebook.  ~Chris

**Comment by cethenmc** [comment]
Hi, Jamie.  I got to this assignment tonight yet.  It works when pressing the play button, I am sure.  However, I would like you to be able to run this from the command line. If your shbang line is in their correctly, then please go to week2 and execute the following command to modify the rights.

chmod u+x first-script.py

Then execute the file from command line.

./first-script.py

If it renders results, then...
    1. add the file to staging (git add .)
    2. commit the file to your local repo. (git commit -m "changes requested to run from command line")
    3. push to the git hub repository (git push)
    4. reply to this same issue, saying you have completed these steps

Thanks.

~Chris

**Comment by jsummerfield-matc** [comment]
completed the steps you listed and it works great! :) I will make sure as well to create two issues next time!

**Comment by cethenmc** [comment]
Thanks, Jamie.  Looks good! ~Chris
