### ISSUE TITLE
Week 12 assignments complete!

### ISSUE THREAD

**Issue by jsummerfield-matc** [madisoncollege-it-programs/python-scripting-jsummerfield-matc#14]

**Comment by cethenmc** [comment]
Hi, Jamie.  I will record a 6 of 8 for now on this one.  Please resubmit to this issue when corrected, or please reply letting me know you will keep the 6 out of 8.

We have three labs beginning Thursday, where you could troubleshoot and ask questions.  Below are the problems.

For the Chat:  It errors on the second chat entry every time.
![image](https://user-images.githubusercontent.com/112707666/204853063-294109f7-6062-44f8-9054-abee6a65edaf.png)

For the File Transfer, it is pretty good.  There is an end of the file line feed missing when I diff between the sillywords.txt and the serverRead.txt.  Therefore, a character is dropped.  The other thing is that the filetransfer-client does not exit after the copy.  It stays in a running s

**Comment by cethenmc** [comment]
Time expired.  Closing ticket.
