### ISSUE TITLE
Week 13 assignments ready for grading!

### ISSUE THREAD

**Issue by jsummerfield-matc** [madisoncollege-it-programs/python-scripting-jsummerfield-matc#15]

**Comment by cethenmc** [comment]
This looks good.  The directions were not very clear in that when it was asking to get every link it was really wanting the href, as well.  With the directions being unclear, I accept just the link name like you provide.  I would also accept just the links.  In an ideal world I would see both.  If you would like to add to your own, change your print statement to:

print(f"{link.text}:  {link.get('href')}")

Nice work.  8 out of 8.
