### ISSUE TITLE
Final Project finished

### ISSUE THREAD

**Issue by jsummerfield-matc** [madisoncollege-it-programs/python-scripting-jsummerfield-matc#16]
Couldn't get sockets working, but after hours of trying everything i had and searching the internet, i figured i wouldn't be done in time so I am taking the hit on it. Everything else went fine :) 

THANK YOU for all the help this past semester and have a great winter break!

**Comment by cethenmc** [comment]
![image](https://user-images.githubusercontent.com/112707666/208182849-90f29658-1037-4f09-afe4-338fa3d51886.png)
