### ISSUE TITLE
Week 6 assignments are ready for grading!

### ISSUE THREAD

**Issue by jsummerfield-matc** [madisoncollege-it-programs/python-scripting-jsummerfield-matc#5]
have fun with the flowers! :)

**Comment by cethenmc** [comment]
boolean.py = full credit.

flowcontrol.py = You should give multiple options under the third door option.  Have at least two choices with and else in case they don't choose from the options.  Also, the prompting question doesn't give what the choices are (I tried a 1 (boolean yes), 'y', until I finally hit yes.  Please clean that up a little bit and resubmit.

Holding at a 6 of 8 until you resubmit.  Thanks. ~Chris

**Comment by cethenmc** [comment]
Jamie - I just ran this again, and I did not read carefully enough that you did have a yes/no question in there.  Switching to 8 of 8.

**./flowcontrol.py** 
You enter a dark room with two doors. 
Do you go through door #1, #2 or #3?
**-> 3**
You enter through the door and see a field, full of flowers, it is bright and sunny, will you go and smell one?
**yes**
You smell a smell of gasoline smelling from the flower, suddenly your head explodes...rest in peace.

**./flowcontrol.py** 
You enter a dark room with two doors. 
Do you go through door #1, #2 or #3?
**-> 3**
You enter through the door and see a field, full of flowers, it is bright and sunny, will you go and smell one?
**no**
Yea those flowers were weird anyway.

**$ ./flowcontrol.py** 
You enter a dark room with two doors. 
Do you go through door #1, #2 or #3?
**-> 3**
You enter through the door and see a field, full of flowers, it is bright and sunny, will you go and smell one?
**maybe**
Yea those flowers were weird anyway.
student@python-client:~/Repo/InPerson/python-scripting-jsummerfield-matc/week6$
