### ISSUE TITLE
midterm 1 if complete

### ISSUE THREAD

**Issue by jsummerfield-matc** [madisoncollege-it-programs/python-scripting-jsummerfield-matc#9]

**Comment by cethenmc** [comment]
All concepts you used were concepts learned in class, which was nice to see.  I assume you could not recall a method to extract the line number as requested.  As a result of not extracting the line number (2 pts) and converting it to an int (2 pts) which was a hint to help you know what you might use to extract), you will receive 4 less points.  And you also did not print out your name as asked (1 pt).  Your score is 28/33.
